package terror

const (
	ERROR_CODE_PARAMETER      = "01"
	ERROR_CODE_DATA_NOT_FOUND = "02"
	ERROR_CODE_INVALID_RULE   = "03"
	ERROR_CODE_SYSTEM         = "99"

	ERROR_TYPE_PARAMETER      = "ERROR PARAMETER"
	ERROR_TYPE_DATA_NOT_FOUND = "ERROR DATA NOT FOUND"
	ERROR_TYPE_INVALID_RULE   = "ERROR INVALID RULE"
	ERROR_TYPE_SYSTEM         = "ERROR SYSTEM"

	ERROR_DEFAULT_MESSAGE_PARAMETER      = "Parameter Error"
	ERROR_DEFAULT_MESSAGE_DATA_NOT_FOUND = "Data not found"
	ERROR_DEFAULT_MESSAGE_INVALID_RULE   = "Invalid Rule Error"
	ERROR_DEFAULT_MESSAGE_SYSTEM         = "System Error"
)
