version: '3.8'

services:

  database:
    platform: linux/x86_64
    image: mysql:8.0.28
    container_name: app_mysql
    ports:
      - 3334:3306
    environment:
      - MYSQL_ROOT_HOST=localhost
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
